name = "particle"
description = "Particle theme for Zola"
license = "MIT"
homepage = "https://github.com/svavs/particle-zola"
min_version = "0.16.1"
demo = "https://particle-zola.vercel.app/"

[author]
name = "Silvano Sallese"
homepage = "https://svavs.github.io/"

[original]
author =  "Anon Developer"
homepage = "https://nrandecker.github.io/particle/"
repo = "https://github.com/nrandecker/particle" 

[extra]

